"""Baseline schema

Revision ID: 0001
Revises:
Create Date: 2026-09-13

Squashed baseline covering every table the models define.

The chain this replaces was unrunnable: revision 003 declared
`down_revision = '002'`, and revisions 001 and 002 were not in the repository,
so `alembic upgrade head` died with `KeyError: '002'`. Every database this app
has ever had was built by `Base.metadata.create_all` at startup instead, which
is why nobody noticed.

**On a database that already has the schema** (which is every existing
deployment, because create_all made it), do NOT run `upgrade head` — it will try
to create tables that exist. Run this once instead:

    alembic stamp head

That records the baseline as applied without touching anything. Schema changes
from here get ordinary revisions on top.
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espn_player_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('position_name', sa.String(length=10), nullable=True),
    sa.Column('pro_team_id', sa.Integer(), nullable=True),
    sa.Column('pro_team_abbr', sa.String(length=10), nullable=True),
    sa.Column('eligible_slots', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('injury_status', sa.String(length=50), nullable=True),
    sa.Column('season_stats', sa.JSON(), nullable=True),
    sa.Column('last_week_points', sa.Float(), nullable=True),
    sa.Column('season_points', sa.Float(), nullable=True),
    sa.Column('average_points', sa.Float(), nullable=True),
    sa.Column('latest_news', sa.Text(), nullable=True),
    sa.Column('news_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_espn_player_id'), 'players', ['espn_player_id'], unique=True)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('espn_s2_encrypted', sa.Text(), nullable=True),
    sa.Column('espn_swid_encrypted', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('ESPN', 'SLEEPER', name='platformtype'), nullable=False),
    sa.Column('espn_league_id', sa.Integer(), nullable=True),
    sa.Column('sleeper_league_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('scoring_type', sa.String(length=50), nullable=True),
    sa.Column('roster_settings', sa.JSON(), nullable=True),
    sa.Column('scoring_settings', sa.JSON(), nullable=True),
    sa.Column('espn_s2_encrypted', sa.Text(), nullable=True),
    sa.Column('espn_swid_encrypted', sa.Text(), nullable=True),
    sa.Column('sleeper_user_id', sa.String(length=255), nullable=True),
    sa.Column('current_week', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_synced', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_espn_league_id'), 'leagues', ['espn_league_id'], unique=False)
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_index(op.f('ix_leagues_platform'), 'leagues', ['platform'], unique=False)
    op.create_index(op.f('ix_leagues_sleeper_league_id'), 'leagues', ['sleeper_league_id'], unique=False)
    op.create_table('board_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('POST', 'WEEKLY_RECAP', 'POWER_RANKINGS', 'AWARDS', 'TRASH_TALK', 'SEASON_RECAP', 'DIGEST', name='postkind', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('media_paths', sa.JSON(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=True),
    sa.Column('generated_by', sa.String(length=120), nullable=True),
    sa.Column('allow_training', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_posts_author_user_id'), 'board_posts', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_board_posts_created_at'), 'board_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_board_posts_id'), 'board_posts', ['id'], unique=False)
    op.create_index('ix_board_posts_league_created', 'board_posts', ['league_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_board_posts_league_id'), 'board_posts', ['league_id'], unique=False)
    op.create_table('league_content_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('voice_guide', sa.Text(), nullable=True),
    sa.Column('humor_examples', sa.JSON(), nullable=True),
    sa.Column('personas', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_content_profiles_id'), 'league_content_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_league_content_profiles_league_id'), 'league_content_profiles', ['league_id'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('espn_team_id', sa.Integer(), nullable=True),
    sa.Column('sleeper_roster_id', sa.Integer(), nullable=True),
    sa.Column('sleeper_owner_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('nickname', sa.String(length=255), nullable=True),
    sa.Column('abbreviation', sa.String(length=10), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('ties', sa.Integer(), nullable=True),
    sa.Column('points_for', sa.Float(), nullable=True),
    sa.Column('points_against', sa.Float(), nullable=True),
    sa.Column('current_roster', sa.JSON(), nullable=True),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_id'), 'teams', ['id'], unique=False)
    op.create_table('board_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['board_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['board_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_board_comments_created_at'), 'board_comments', ['created_at'], unique=False)
    op.create_index(op.f('ix_board_comments_id'), 'board_comments', ['id'], unique=False)
    op.create_index(op.f('ix_board_comments_post_id'), 'board_comments', ['post_id'], unique=False)
    op.create_table('matchups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchup_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=True),
    sa.Column('away_team_id', sa.Integer(), nullable=True),
    sa.Column('home_score', sa.Float(), nullable=True),
    sa.Column('away_score', sa.Float(), nullable=True),
    sa.Column('home_projected_score', sa.Float(), nullable=True),
    sa.Column('away_projected_score', sa.Float(), nullable=True),
    sa.Column('is_playoff', sa.Boolean(), nullable=True),
    sa.Column('winner', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchups_id'), 'matchups', ['id'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('proposing_team_id', sa.Integer(), nullable=False),
    sa.Column('receiving_team_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('proposed_players', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELLED', name='tradestatus'), nullable=True),
    sa.Column('fairness_score', sa.Float(), nullable=True),
    sa.Column('value_difference', sa.Float(), nullable=True),
    sa.Column('analysis_summary', sa.Text(), nullable=True),
    sa.Column('espn_trade_id', sa.String(length=100), nullable=True),
    sa.Column('processed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['proposing_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['receiving_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_id'), 'trades', ['id'], unique=False)
    op.create_table('voice_samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('source_post_id', sa.Integer(), nullable=True),
    sa.Column('author_user_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_post_id'], ['board_posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_samples_id'), 'voice_samples', ['id'], unique=False)
    op.create_index(op.f('ix_voice_samples_league_id'), 'voice_samples', ['league_id'], unique=False)
    op.create_index('ix_voice_samples_league_score', 'voice_samples', ['league_id', 'score'], unique=False)
    op.create_table('waiver_budgets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('current_budget', sa.Float(), nullable=True),
    sa.Column('spent_budget', sa.Float(), nullable=True),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_budgets_id'), 'waiver_budgets', ['id'], unique=False)
    op.create_table('waiver_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waiver_transactions_id'), 'waiver_transactions', ['id'], unique=False)
    op.create_table('board_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('comment_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.Enum('SAVAGE', 'FUNNY', 'BRUTAL', 'SMART', 'COLD', name='reactionkind', native_enum=False, length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('(post_id IS NOT NULL AND comment_id IS NULL) OR (post_id IS NULL AND comment_id IS NOT NULL)', name='ck_board_reactions_one_target'),
    sa.ForeignKeyConstraint(['comment_id'], ['board_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['board_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'comment_id', 'reaction', name='uq_board_reaction_comment'),
    sa.UniqueConstraint('user_id', 'post_id', 'reaction', name='uq_board_reaction_post')
    )
    op.create_index(op.f('ix_board_reactions_comment_id'), 'board_reactions', ['comment_id'], unique=False)
    op.create_index(op.f('ix_board_reactions_id'), 'board_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_board_reactions_post_id'), 'board_reactions', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_board_reactions_post_id'), table_name='board_reactions')
    op.drop_index(op.f('ix_board_reactions_id'), table_name='board_reactions')
    op.drop_index(op.f('ix_board_reactions_comment_id'), table_name='board_reactions')
    op.drop_table('board_reactions')
    op.drop_index(op.f('ix_waiver_transactions_id'), table_name='waiver_transactions')
    op.drop_table('waiver_transactions')
    op.drop_index(op.f('ix_waiver_budgets_id'), table_name='waiver_budgets')
    op.drop_table('waiver_budgets')
    op.drop_index('ix_voice_samples_league_score', table_name='voice_samples')
    op.drop_index(op.f('ix_voice_samples_league_id'), table_name='voice_samples')
    op.drop_index(op.f('ix_voice_samples_id'), table_name='voice_samples')
    op.drop_table('voice_samples')
    op.drop_index(op.f('ix_trades_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_matchups_id'), table_name='matchups')
    op.drop_table('matchups')
    op.drop_index(op.f('ix_board_comments_post_id'), table_name='board_comments')
    op.drop_index(op.f('ix_board_comments_id'), table_name='board_comments')
    op.drop_index(op.f('ix_board_comments_created_at'), table_name='board_comments')
    op.drop_table('board_comments')
    op.drop_index(op.f('ix_teams_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_league_content_profiles_league_id'), table_name='league_content_profiles')
    op.drop_index(op.f('ix_league_content_profiles_id'), table_name='league_content_profiles')
    op.drop_table('league_content_profiles')
    op.drop_index(op.f('ix_board_posts_league_id'), table_name='board_posts')
    op.drop_index('ix_board_posts_league_created', table_name='board_posts')
    op.drop_index(op.f('ix_board_posts_id'), table_name='board_posts')
    op.drop_index(op.f('ix_board_posts_created_at'), table_name='board_posts')
    op.drop_index(op.f('ix_board_posts_author_user_id'), table_name='board_posts')
    op.drop_table('board_posts')
    op.drop_index(op.f('ix_leagues_sleeper_league_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_platform'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_espn_league_id'), table_name='leagues')
    op.drop_table('leagues')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_players_id'), table_name='players')
    op.drop_index(op.f('ix_players_espn_player_id'), table_name='players')
    op.drop_table('players')
    # ### end Alembic commands ###